openapi: 3.0.0
info:
  title: HR Portal API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a welcome message
      responses:
        '200':
          description: A welcome message is returned
          content:
            text/plain:
              schema:
                type: string
